### ISSUE TITLE
No screen to allow access

### ISSUE THREAD

**Issue by aurel2222** [JordiCorbilla/FlickrPhotoStats#5]
Hi,
To start, I'm very admirative of the huge work you did for this app... congratulations...

I'm sorry to bring a problem. 
I download and unzip the app. Then I found in an other app (FlickrContactsStats) the files for the libraries. The links you gave are obselete. I found link to openssl but can't download it. 

I open the app, but the window to Authenticate with flickr doesn't come (step 5). 

Then the app is opening and with empty boxes.

Could you help me please ? thanks !

**Comment by JordiCorbilla** [comment]
Hi,

Did you check in the release area of this project? Just checking that you are currently using the latest version available.

Cheers,
Jordi

**Comment by aurel2222** [comment]
Hi,
I'm using the Version 4.8.0.2 (RC stable) version.

cheers,
Aelis

**Comment by JordiCorbilla** [comment]
Ahh I think what's going on. The application uses an embedded IE component and the latest version of Flickr doesn't support IE anymore, only modern browsers. I still need to figure out how to fix that. Apologies for the late response.

**Comment by aurel2222** [comment]
You do not need to apologize when you offer your time and work to communauty.

Portate bien, creo que estas en España. Soy de Francia.  Cuidate en estos momentos dificiles !

**Comment by decembre** [comment]
Any new about this problem?

I test  your app.
After downloaded SSL dll  from <a href="https://indy.fulgan.com/SSL/Archive/Experimental/">[Index of /SSL/Archive/Experimental](https://indy.fulgan.com/SSL/Archive/Experimental/)</a>, because your link provided don't work.
I install it , but as said before, i can't authorize it.

It seems you use always IE for that ?

So, have you plan something new around that ?

**Comment by JordiCorbilla** [comment]
@decembre I'm sorry but no, I don't have a solution for it. Delphi doesn't have a component yet (that I know of) that would allow me to use another browser instead of IE. I'm having the same problem as I cannot run this on a modern OS. I'm having to run the whole thing under a windows server 2008 to overcome this for now.

I haven't checked if the latest version available has a different component that I might be able to use. As of now, I might have to see if there any other alternative available (like moving some parts to web instead).

**Comment by decembre** [comment]
> @decembre I'm sorry but no, I don't have a solution for it. 

Hoo, that's not your fault:

Damn Delphi and Flickr to not make something compatible with IE (i never user it, i use Waterfox).
I feel they don't take care too much of the need of their Free devs.

Hmm, wait and see and thanks for your quick reply.

And sorry, It seems i make an mistake:
It seems you are Spanish ?
So greeting from France.

**Comment by JordiCorbilla** [comment]
I feel the same, it's been a while since I coded in Delphi, mostly because there is a push to do everything .net nowadays and I feel the pain.
Yeah Spanish here, greetings from the UK.

let's see if I can find a solution for it soon!

Thanks for checking in
